Imageplayer keeps player instance on slice position change
vvvv/vvvv-sdk pull request #289
Opened 2017-05-15 19:13 UTC by woeishi

was previously discarding preloaded data if dir input changed to another slice

2017-05-16 14:02 UTC, azeno requested changes
Just a few minor code simplifications. Otherwise it looks good.

2017-05-16 14:02 UTC, azeno commented on vvvv45/src/nodes/plugins/Texture/ImagePlayer/PlayerNode.cs
> +            var oldPlayers = new List<ImagePlayer>(FImagePlayers.ToList());
var oldPlayers = FImagePlayers.ToList();

2017-05-16 14:02 UTC, azeno commented on vvvv45/src/nodes/plugins/Texture/ImagePlayer/PlayerNode.cs
> +                var player = oldPlayers.Where(p => p.Directories.SpreadEqual(FDirectoryIn[i])).DefaultIfEmpty(null).First();
var player = oldPlayers.FirstOrDefault(p => p.Directories.SpreadEqual(FDirectoryIn[i]));

2017-05-16 18:30 UTC, woeishi commented
here you go

 List<ImagePlayer> oldPlayers =... because vs was complaining in the foreach below that ? doesn't implement GetEnumerator

2017-05-18 20:06 UTC, merged

2017-05-18 20:06 UTC, azeno commented
Thanks!